#!/usr/bin/env node

var mongo = require('mongodb');

const mongoHost = process.env.MONGO_HOST;
const mongoPort = process.env.MONGO_PORT;
const mongoUsername = process.env.MONGO_USERNAME;
const mongoPassword = process.env.MONGO_PASSWORD;
const mongoDatabase = process.env.MONGO_DATABASE;

const uri = `mongodb://${mongoUsername}:${mongoPassword}@${mongoHost}:${mongoPort}`;

async function tryConnect() {
    var client = null;
    console.log("Connecting to database...");
    while (!client) {
        try {
            client = await mongo.connect(uri);
            console.log("Connected to database");
        } catch (ex) {
            console.log("Failed connecting to database. Retrying...");
            await new Promise(resolve => setTimeout(resolve, 1000));
        }
    }
    var db = client.db(mongoDatabase);
    console.log("Adding user");
    await db.addUser(mongoUsername, mongoPassword, {
        roles: [{ role: 'readWrite', db: mongoDatabase }]
    });
    console.log("Added user");
    process.exit(0);
}

tryConnect();