#!/usr/bin/env node

var mongo = require('mongodb');

const mongoHost = process.env.MONGO_HOST;
const mongoPort = process.env.MONGO_PORT;
const mongoUsername = process.env.MONGO_USERNAME;
const mongoPassword = process.env.MONGO_PASSWORD;

console.log("Connecting to database");

async function tryConnect() {
    try {
        await mongo.connect(
            `mongodb://${mongoUsername}:${mongoPassword}@${mongoHost}:${mongoPort}`, {
            useUnifiedTopology: true
        });
        console.log("Connected to database");
        process.exit(0);
    } catch (ex) {
        console.log("Failed connecting to database. Retrying...");
        setTimeout(tryConnect, 1000);
    }
}

tryConnect();